[project]
name = "my-project"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
my-project = "my_project:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyter==1.1.1",
]
